### ISSUE TITLE
`showRowHeaders: false` and setData breaks DataGrid

### ISSUE THREAD

**Issue by gerricom** [DataGridXL/DataGridXL#18]
First things first: I tested all those datagrids and table libraries out there and I really like your's especially because of its minimalism and performance! Thanks for creating this piece of software!

For my use case I built a little svelte component wrapped around DataGrid, but I can reproduce the problem within your API playground. To do this proceed like this:

First create a new custom playground:
```javascript
var options = {
    showRowHeaders: false,
};
```
Now add data to the grid:
```javascript
playground.setData([{"id":1,"first_name":"Latisha","last_name":"Vince","email":"lvince0@techcrunch.com","gender":"Female","ip_address":"12.92.111.97"},{"id":2,"first_name":"Deana","last_name":"Colquite","email":"dcolquite1@google.ru","gender":"Female","ip_address":"67.85.91.50"},{"id":3,"first_name":"Clemmy","last_name":"Morgen","email":"cmorgen2@phoca.cz","gender":"Female","ip_address":"94.222.121.12"}])
```

You now will see the first part of the problem. The upper most left cell is labeled with `id` but has an overlay of the unnamed first column `A`:

![2021-08-10_13-28-28](https://user-images.githubusercontent.com/459469/128859256-056d48ba-b62e-4bf3-bf0f-f3479b9d61d7.png)

If now (because of reactivity...) the data changes it gets messy:

```
playground.setData([{"id":10,"first_name":"Horatio","last_name":"Trynor","email":"htrynor9@wufoo.com","gender":"Male","ip_address":"124.197.96.23"},{"id":11,"first_name":"Brande","last_name":"MacPadene","email":"bmacpadenea@cargocollective.com","gender":"Female","ip_address":"176.172.122.50"},{"id":12,"first_name":"Bondon","last_name":"Bennough","email":"bbennoughb@squidoo.com","gender":"Male","ip_address":"117.5.12.111"},])
```

![2021-08-10_13-31-52](https://user-images.githubusercontent.com/459469/128859708-b9cd5ad4-a72f-4a50-ae1a-31e93295d4c7.png)

The old first column stays in place.

I guess the library is expecting the first column to be the column with row headers....

**Comment by DataGridXL** [comment]
Hi Markus,

Glad you like our product! I have reproduced your error, and came up with 2 different workarounds:

Option 1: Hide the unwanted column after a `setData` call
https://codepen.io/datagridxl/pen/PomXBOL

Option 2: Create a new grid every time, instead of using `setData`
https://codepen.io/datagridxl/pen/RwVEBEv

(We're super busy with building DGXL v2, so at the stage we offer workarounds instead of fixes).

I would recommend choosing option 2. When you create a new grid with the same container ID, the old grid will be destroyed, and a new grid will appear, with all the correct settings.

Let me know if this helps!

**Comment by gerricom** [comment]
Thanks for that fast response! I've tried both options and for now I'll go with options 1. The downside of option 2 is, that you loose your scroll position if new data is set to the table. This is not happening with option 1.

**Comment by DataGridXL** [comment]
You're right, in that case go for option 1!
