### ISSUE TITLE
bug: in traverse mode, typing " or ' or ~ opens editor, but chars don't display (Chrome browser)

### ISSUE THREAD

**Issue by RobbiesCode** [DataGridXL/DataGridXL#5]
In Firefox no problem. In chrome, typing chars like ", ' or ~ open the editor, but chars do not display. (not as an opening character), even when space is pressed afterwards. In Excel and G Sheets web apps, this issue does not occur.

**Comment by RobbiesCode** [comment]
These keys are called "dead keys"

**Comment by DataGridXL** [comment]
This problem is fixed in DGXLv2 (Q3 2021).

How? The editor node and the clipboard node are now a single element. For dead keys to display, the editor node (input node) has to have focus, before start typing. However, clipboard node also needs focus, for copy/cut/paste to work. So clipboard functions and input field have been merged into a single element.

This also means that we need to add a manuel key combo for ctrl+a, as we cannot use the same "selectAll" trick anymore.
